- name: Install Newman
run:
  npm install -g newman
  npm install -g newman-reporter-htmlextra
  
- name: Make Directory for Results
  run: mkdir -p testResults
  
 - name: Run API Tests
   run: newman run "Restful Booker BVT.postman_collection.json" -e Production.postman_environment.json -r htmlextra --reporter-htmlextra-export ./testResults/report.html
